package sitebuild

import (
	"strings"
	"testing"
)

const goodPlan = `{
  "title": "Water",
  "description": "A council of role-agents.",
  "sections": [
    {"id": "hero", "heading": "Water", "body": "Four roles, one decision.", "bullets": ["deny by default"]},
    {"id": "what-is-water", "heading": "What Water is", "body": "A council, not an assistant.", "bullets": []},
    {"id": "role-agents", "heading": "The council", "body": "", "bullets": ["Frames intent.", "Assigns and verifies.", "Judges feasibility.", "Owns experience."]},
    {"id": "memory-isolation", "heading": "Memory isolation", "body": "Each role remembers alone.", "bullets": []},
    {"id": "orchestration-flow", "heading": "The flow", "body": "CEO frames, COO assigns, CEO decides.", "bullets": []},
    {"id": "safety-model", "heading": "Approved local actions", "body": "Nothing runs unapproved.", "bullets": []},
    {"id": "demo", "heading": "See it run", "body": "Give it a brief.", "bullets": []},
    {"id": "footer", "heading": "", "body": "Built for a demo.", "bullets": []}
  ],
  "theme": {"name": "water base", "background": "#050505", "foreground": "#E8E4D0", "accent": "#D00000"}
}`

// TestBuildSiteRendersExpectedFiles — a valid plan produces exactly the three
// files the renderer owns, carrying every block the page promises.
func TestBuildSiteRendersExpectedFiles(t *testing.T) {
	p, err := ParsePlan(goodPlan)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	files, err := Render(p, "site")
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	if len(files) != 3 {
		t.Fatalf("expected 3 files, got %d", len(files))
	}
	byPath := map[string]string{}
	for _, f := range files {
		byPath[f.Path] = f.Content
	}
	for _, want := range []string{"index.html", "styles.css", "README.md"} {
		if _, ok := byPath[want]; !ok {
			t.Fatalf("missing %s", want)
		}
	}
	html := byPath["index.html"]
	for _, id := range Slots {
		if !strings.Contains(html, `id="`+id+`"`) {
			t.Fatalf("index.html missing block %q", id)
		}
	}
	for _, role := range []string{"CEO", "COO", "CTO", "Design"} {
		if !strings.Contains(html, "<h3>"+role+"</h3>") {
			t.Fatalf("index.html missing role card %q", role)
		}
	}
	if !strings.Contains(html, "Generated by Water") {
		t.Fatal("index.html missing the generated-by mark")
	}
	if !strings.Contains(html, `href="styles.css"`) {
		t.Fatal("index.html does not link its stylesheet")
	}
	// Dependency-free: no external origin is referenced anywhere.
	for _, f := range files {
		if strings.Contains(f.Content, "http://") || strings.Contains(f.Content, "https://") {
			t.Fatalf("%s references an external URL", f.Path)
		}
	}
	if css := byPath["styles.css"]; !strings.Contains(css, "#D00000") {
		t.Fatal("styles.css missing the accent colour")
	}
}

// TestRenderIsDeterministic — the same plan renders byte-identical files, so a
// re-run never produces a spurious overwrite.
func TestRenderIsDeterministic(t *testing.T) {
	p, err := ParsePlan(goodPlan)
	if err != nil {
		t.Fatal(err)
	}
	first, err := Render(p, "site")
	if err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 3; i++ {
		again, err := Render(p, "site")
		if err != nil {
			t.Fatal(err)
		}
		for j := range first {
			if first[j].Path != again[j].Path || first[j].Content != again[j].Content {
				t.Fatalf("render %d differs at %s", i, first[j].Path)
			}
		}
	}
}

// TestRenderEscapesModelContent — page copy is untrusted input. Markup in a
// plan must appear as text, never as structure.
func TestRenderEscapesModelContent(t *testing.T) {
	p, err := ParsePlan(`{"title":"<script>alert(1)</script>","description":"\" onload=\"x",
		"sections":[{"id":"hero","heading":"<img src=x onerror=alert(1)>","body":"<b>bold</b>","bullets":["</ul><script>evil()</script>"]},
		{"id":"role-agents","heading":"Roles","body":"","bullets":["<script>a()</script>","b","c","d"]}],
		"theme":{"name":"x","background":"#000000","foreground":"#ffffff","accent":"#ff0000"}}`)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	files, err := Render(p, "site")
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	for _, f := range files {
		if f.Path != "index.html" {
			continue
		}
		// No model string may open a tag. Attribute-looking text is harmless
		// once the angle brackets are entities.
		for _, bad := range []string{"<script", "<img", "<b>"} {
			if strings.Contains(f.Content, bad) {
				t.Fatalf("index.html contains unescaped %q", bad)
			}
		}
		for _, want := range []string{"&lt;script&gt;", "&lt;img"} {
			if !strings.Contains(f.Content, want) {
				t.Fatalf("index.html did not escape %q as text", want)
			}
		}
	}
}

// TestThemeColoursAreValidated — a colour is a hex value or it is replaced. It
// never reaches the stylesheet as arbitrary text.
func TestThemeColoursAreValidated(t *testing.T) {
	p, err := ParsePlan(`{"title":"T","sections":[{"id":"hero","heading":"H","body":"B"}],
		"theme":{"name":"x","background":"red; } body { background: url(http://evil)","foreground":"","accent":"#abc"}}`)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if p.Theme.Background != defaultBg || p.Theme.Foreground != defaultFg {
		t.Fatalf("bad colours were not replaced: %+v", p.Theme)
	}
	if p.Theme.Accent != "#abc" {
		t.Fatalf("valid short hex was rejected: %q", p.Theme.Accent)
	}
	files, err := Render(p, "site")
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range files {
		if strings.Contains(f.Content, "evil") {
			t.Fatalf("%s carried an injected stylesheet rule", f.Path)
		}
	}
}

// TestRenderFillsMissingSlots — a partial plan still yields a complete page
// rather than an error, and unknown sections are kept rather than dropped.
func TestRenderFillsMissingSlots(t *testing.T) {
	p, err := ParsePlan(`{"title":"T","description":"d",
		"sections":[{"id":"hero","heading":"H","body":"B"},{"id":"extra-thoughts","heading":"Extra","body":"kept"}],
		"theme":{"name":"x","background":"#000000","foreground":"#ffffff","accent":"#ff0000"}}`)
	if err != nil {
		t.Fatal(err)
	}
	files, err := Render(p, "site")
	if err != nil {
		t.Fatal(err)
	}
	html := files[0].Content
	for _, id := range Slots {
		if !strings.Contains(html, `id="`+id+`"`) {
			t.Fatalf("missing slot %q in a partial plan", id)
		}
	}
	if !strings.Contains(html, `id="extra-thoughts"`) || !strings.Contains(html, "kept") {
		t.Fatal("an unrecognised section was dropped")
	}
}
